Output on error

diff --git a/.github/workflows/validate.yml b/.github/workflows/validate.yml
--- a/.github/workflows/validate.yml
+++ b/.github/workflows/validate.yml
@@ -37,12 +37,12 @@ jobs:
         env:
           LICENSE: ${{ secrets.TEST_LICENSE }}
         run: |
-          [[ "$(echo "$LICENSE" | base64 -d | md5sum)" == "e1fd9a7a78a5ddd27e3443f2144a6de3  -" ]]
-          echo "$LICENSE" | base64 -d | curl --silent --form 'file=@-;filename=license' http://localhost:8080/license
+          [[ "$(echo "$LICENSE" | base64 -d | md5sum)" == "e1fd9a7a78a5ddd27e3443f2144a6de3  -" ]] || ( echo "md5sum mismatch"; exit 1 )
+          echo "$LICENSE" | base64 -d | curl --silent --form 'file=@-;filename=license' http://localhost:8080/license || ( echo "license upload failed"; exit 1 )
           sleep 5
-          while curl --silent --fail http://localhost:8080/license/status ; do sleep 1; done
+          while curl --silent --fail http://localhost:8080/license/status ; do sleep 1; done 
           sleep 10
-          curl --silent --fail http://localhost:8080/api/test
+          curl --silent --fail http://localhost:8080/api/test || ( echo "api test failed"; exit 1 )
       - name: Use Node.js 10.20.1
         uses: actions/setup-node@v1
         with:
